### ISSUE TITLE
trouble with Install EVE

### ISSUE THREAD

**Issue by anton-bondarev** [lf-edge/eve#1684]
I have trouble with EVE building

When I do 'make live' It seems that It failed because `Could not pull image linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64`
```make live
Creating go builder image for user anton
eve-build-anton docker container is ready to use
cd /home/anton/git/eve/dist/amd64/installer ; _() { C=`docker create $1 fake` ; shift ; docker export $C | tar -xf - "$@" ; docker rm $C ; } ; _ lfedge/eve-u-boot:d4c47072ebe9022d8bfd9e41077b755afd7520d8-amd64 boot
f58500191d7fad25505dee6b6908346de74884e5af126e866aa522979d01dd4f
cd /home/anton/git/eve/dist/amd64/installer ; _() { C=`docker create $1 fake` ; shift ; docker export $C | tar -xf - "$@" ; docker rm $C ; } ; _ lfedge/eve-grub:d77ecff8639aa6d3b7a06641b21907a8afc74f76-amd64 EFI
992e1ee514e7f230ae8172e85df8e1761123d67b8c5b88607209a5e58898e404
Done building /home/anton/git/eve/build-tools/bin/linuxkit
./tools/makerootfs.sh images/rootfs-xen.yml /home/anton/git/eve/dist/amd64/installer/rootfs-0.0.0-master-d4574c69-xen-amd64.squash squash
Extract kernel image: lfedge/eve-kernel:3382d12597cbef7d637d616cc7c7617c012b92d4-amd64
Add init containers:
Process init image: linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64
FATA[0006] Failed to build init tarball from linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64: Could not pull image linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64: Trusted pull for linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64 failed: client is offline
./lib/modules/5.4.51-linuxkit/extra/xr_usb_serial_common.ko: Truncated input file (needed 216 bytes, only 0 available)
bsdtar: Error exit delayed from previous errors.
make: *** [Makefile:524: /home/anton/git/eve/dist/amd64/installer/rootfs-0.0.0-master-d4574c69-xen-amd64.squash] Error 1
rm images/rootfs-xen.yml images/rootfs-xen.yml.in
```
But if I do 'docker pull' It is successful
```
docker pull linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64
a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64: Pulling from linuxkit/init
Digest: sha256:ddf114c6ef6b81ab3ceebeabad006d4875a2ea3e0affb06b332dc2b2da53fa23
Status: Image is up to date for linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64
docker.io/linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c-amd64
```

My environment details
```anton@antonnotebook:~/git/eve$ uname -a 
Linux antonnotebook 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
anton@antonnotebook:~/git/eve$ docker --version 
Docker version 19.03.13, build 4484c46d9d
anton@antonnotebook:~/git/eve$ go version
go version go1.15.5 linux/amd64
```

**Comment by rvs** [comment]
Couple of observations:
  1. most of out developers are on Mac OS X (hence your help with making Linux as a dev platform will be greatly appreciated)
  2. *Trusted pull for* is very suspiciously reminding us of a linuxkit trust issues that @deitch is working on upstream

In fact, I'm pretty sure #2 is actually very much the culprit here -- we're stuck with the trust model that linuxkit is enforcing upon us via Docker Notary. It is, by itself, may not be a huge deal but it becomes a pretty big deal when we are trying to do "cross-build" and pull `-amd64` type of artifacts. All of that, again, is what @deitch is working on and could comment.

Ultimately, until this is fixed upstream (few weeks from what I understand) we're sort of stuck with various workarounds. Last time it happened I believe @eriknordmark (the only other developer using Linux as a dev platform day in and day out) had to completely blow up his Docker cache and then it started working again (I maybe fuzzy on details -- @eriknordmark can probably say more here).

**Comment by eriknordmark** [comment]
The issues I have from time to time seem to be related to very slow DNS service from my ISP.; @deitch has verified that linuxkit has a low timeout when doing the (trusted) pull.

 Sometimes it helps to change the DNS server (to 8.8.8.8) and sometimes not. And after a while the problem goes away.

**Comment by anton-bondarev** [comment]
Thanks a lot!

> Sometimes it helps to change the DNS server (to 8.8.8.8) and sometimes not. And after a while the problem goes away.
It works of me!
