### ISSUE TITLE
Insufficient isolation between eve-user-apps

### ISSUE THREAD

**Issue by europaul** [lf-edge/eve#4303]
#### Describe the bug

Right now we are creating eve-user-app tasks from the xen-tools rootfs on disk. Although xen-tools rootfs is mounted as read-only inside those containers, when bind mounting e.g. volumes inside eve-user-app containers the mount procedure creates empty stabs for files / directories being mounted in the original xen-tools rootfs. This can lead to clashes.

#### Recent release

Is it reproducible on a recent release? (See the [list of releases](https://github.com/lf-edge/eve/releases))
yes

#### How to reproduce
* EVE-OS version [e.g., 6.6.3]: 13.3.0
* EVE-OS hardware architecture [e.g., arm64, amd64]: any

Consider the following example: we create two VMs - VM1 mounts additionally a qcow as volume, VM2 mounts additionally a container as volume.
The first VM wants to mount it's qcow inside the eve-user-app task as `/persist/clear/volumes/1f7f92b1-b0b3-47ef-a11a-292f1e2c8bcf.qcow2:/mnt/rootfs/dev/eve/volumes/by-id/1`, which results in an empty file being created also at `/containers/services/xen-tools/rootfs/mnt/rootfs/dev/eve/volumes/by-id/1`.
Now the second VM wants to mount it's container volume inside the eve-user-app task as `/persist/clear/volumes/1f7f92b1-b0b3-47ef-a11a-292f1e2c8bcf#0.container/rootfs:/mnt/rootfs/dev/eve/volumes/by-id/1`, which should result in an empty directory (!) being created also at `/containers/services/xen-tools/rootfs/mnt/rootfs/dev/eve/volumes/by-id/1`.
However `/containers/services/xen-tools/rootfs/mnt/rootfs/dev/eve/volumes/by-id/1` already exists as a file which leads to a clash.

#### Expected behavior

User apps with different mount types (also multi-attach volume mounts) can be started successfully.

#### Error message

`failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/persist/clear/volumes/1f7f92b1-b0b3-47ef-a11a-292f1e2c8bcf#0.container/rootfs" to rootfs at "/mnt/rootfs/dev/eve/volumes/by-id/1": mount /persist/clear/volumes/1f7f92b1-b0b3-47ef-a11a-292f1e2c8bcf#0.container/rootfs:/mnt/rootfs/dev/eve/volumes/by-id/1 (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown`

**Comment by deitch** [comment]
Because it is confused. 😁 

Every container needs its root filesystem somewhere, and almost always a writable (even if just in memory) filesystem. If you want to make it read-only, or reuse, then use an overlayfs, which we do pretty much everywhere.

We need a common root for the VM-shim filesystems, so we use xen-tools (@europaul explained why that one, tools for the VM, I think?).

What we did - and therefore where we went wrong - is that instead of creating a new overlayfs mount for _each_ container, and then using that individual per-container mount for each container, we reused the existing overlayfs mount that xen-tools was using for all of the containers. We shared the (read-write) _overlay_ mount rather then the (read-only) _lower_ to make a new overlayfs for each container. Thus, they trounce each other. They possibly could have messed up the xen-tools as well (I am kind of surprised they didn't). Oops. 😬 

There are two possible solutions:

1. Create a new overlayfs for each container, using the same (read-only) lower as the existing xen-tools one. This is exactly what containerd does when it creates snapshots for a container.
2. Since we already have containerd, and it does all of that dirty work for us, we even use it for other parts, just reuse it. Create an image for xen-tools, load it into containerd, and just ask containerd to do it.

Does that help? @europaul would know more.

**Comment by OhmSpectator** [comment]
Thanks for the comments! Yep, I get the idea, but not in all the details, as I'm still not that good at all these concepts of overlays, low ones, snapshots, etc. But nevertheless.

I put my further questions here: https://github.com/lf-edge/eve/pull/4304#pullrequestreview-2335924424

You partially answered the first question about possible solutions. I just want to understand why we have chosen the second option of perpetuating an image. I think we can discuss it in the PR itself.
