### ISSUE TITLE
`make build-tools` isn't compatible with MacOS 

### ISSUE THREAD

**Issue by antweiss** [lf-edge/eve#447]
# Description

`make build-tools ` makes use of user/group definitions from the host machine to pass into the build container. On my Mac this has caused multiple issues causing me to debug this repeatedly until I finally built the image.

First issue: my group name on a corporate Mac when connected to corporate network was "CORP\Domain Users"
This caused docker command to fail with `"docker build" requires exactly 1 argument.`

I tried to solve this by disconnecting from corporate network.
But this caused the next issue:
`Step 11/19 : RUN addgroup -g ${GID} ${GROUP} && adduser -h /home/${USER} -G ${GROUP} -D -H -u ${UID} ${USER}
 ---> Running in 83210242843f
addgroup: number 798879916 is not in 0..256000 range`

So evidently a high group number supported on MacOS isn't supported in whatever Linux that the go image is based upon.

I siwtched group name and id to staff/20 (the default for MacOS users) and then hit the same issue on my UID

`adduser: number 451220269 is not in 0..256000 range`

So in the end I had to change both the user and group name and id to something of my choosing in the Makefile.

Then I could finally build the image.

# Steps to Reproduce
Run `make build-tools` on a Mac connected to a corporate network with UID/GID not in 0..256000 range.
# Actual Results
Build fails. See description
# Expected Results
Build succeeds.

**Comment by rvs** [comment]
Hey @antweiss -- thanks for reporting this -- much appreciated. Quick observation: now that I'm thinking about this -- none of this trickery is even required on Mac OS since the GID/UID is always that of a user (since there's no native Docker on MacOS -- it all runs in a VM). This is very much required on Linux (and possibly Windows with WSL).

So... a question: you mentioned that you actually ended up working around it? Care to send me the diff?

**Comment by antweiss** [comment]
Submitted a PR
